import React from 'react'
import "../styles/home.css"
import { Link } from 'react-router-dom'
const Home = () => {
  return (
    <>
    <div className="container">
        <div className="lefthome">
            <Link to={'/signup'}><h2>SignUp</h2></Link>
            <Link to={'/login'}><h2>Login</h2></Link>
            <Link to={'/settings'}><h2>Settings</h2></Link>
            <Link to={'/profile'}><h2>Profile</h2></Link>
        </div>
        <div className="righthome">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Mollitia praesentium minus quos doloremque laboriosam tempora nostrum fuga amet iusto maxime vel esse voluptas in, numquam deleniti culpa corporis dolorum deserunt.
            Nisi, beatae tenetur deleniti earum cum a sed similique voluptas, quibusdam neque consectetur quam error veniam quia sequi quo. Id sed illo aspernatur provident adipisci hic fuga modi exercitationem! Molestias.
            Fugiat tempore odit consequuntur, accusantium voluptas eum quia ut ipsam neque dolores repudiandae harum ducimus nihil iusto, porro deleniti, explicabo molestiae sunt aspernatur labore delectus magni facilis! Sint, consequuntur placeat!
            Aut, praesentium veritatis harum expedita consequuntur, itaque quae, iusto quas inventore incidunt blanditiis. Eaque nesciunt obcaecati rem reprehenderit quis ratione ullam saepe necessitatibus quia laboriosam? Laboriosam repudiandae modi blanditiis doloribus!
            Fugiat perspiciatis, laboriosam quia vel suscipit, dicta praesentium unde placeat fuga sint, ex quasi corporis labore repellendus blanditiis quisquam. Aliquid quis nesciunt velit cumque officia! A veritatis quasi asperiores quaerat!
            Illum architecto quam repellat officiis voluptatem porro optio totam voluptate sunt dignissimos deleniti libero nesciunt quibusdam laborum laudantium, ipsa cupiditate nihil velit aperiam exercitationem dicta. Libero rerum impedit velit nisi?
            Maxime laboriosam voluptas, non tempore ratione dolorum neque, ex quae, cum pariatur quod illum. Aperiam, dolores nobis nam earum ullam quod in modi placeat cum saepe itaque natus harum consectetur.
            Recusandae ad hic nam dolorem ducimus nemo odio reiciendis, corporis impedit inventore nesciunt temporibus distinctio aut omnis dolorum perferendis adipisci tenetur a natus molestiae, numquam corrupti. Vel mollitia voluptas voluptates!
            Nostrum adipisci distinctio magni sit veritatis dolore eaque sunt, aperiam tempore repellat fugiat vero sequi, culpa reprehenderit sed fuga odio vitae dolores beatae accusantium. Optio veritatis dolorem neque cumque maxime.
            Quia excepturi obcaecati sit ea eligendi delectus iusto enim deleniti quos impedit cum laborum quas illo ab, quibusdam explicabo hic temporibus sunt rem nihil ullam unde voluptatum deserunt. Architecto, natus.
            Ducimus ipsum odio, saepe sed amet consequuntur nesciunt laborum optio, dolorem tempora excepturi voluptates. Molestias asperiores rem ex iure repellendus magnam, quia non hic praesentium? Amet non eum aperiam a.
            Inventore rerum non tempora, quisquam quasi maxime. Eum vel iure mollitia dignissimos commodi veniam quod, doloribus qui maxime architecto inventore quaerat velit ipsum corporis numquam iusto enim labore porro reprehenderit?
            Obcaecati nesciunt magnam perspiciatis tempore explicabo blanditiis sequi incidunt veritatis, facere mollitia inventore accusamus at eum dignissimos maxime sit quam ducimus error ut odio est voluptatibus vitae nostrum quibusdam. Voluptatibus.
            Rerum quibusdam mollitia fugit blanditiis! Sequi fugiat at praesentium libero quas suscipit minima modi ut delectus quisquam ad beatae necessitatibus explicabo alias rerum fuga nam repellendus, repudiandae obcaecati corrupti nesciunt?
            Eaque accusantium facilis dolores numquam, minus nobis illum non optio voluptatibus vero incidunt animi magnam? Officiis odit repellendus molestias sequi aperiam cupiditate natus porro deserunt perferendis! Distinctio placeat exercitationem illo?
            Laborum odit sapiente amet autem voluptates doloremque totam laudantium labore incidunt, itaque veritatis numquam, maxime vel non asperiores quod ipsum libero placeat vitae distinctio consequatur cupiditate? Tenetur nostrum quibusdam doloremque.
            Id tenetur exercitationem quos laudantium excepturi iusto voluptatibus eligendi libero quis? Libero corrupti temporibus asperiores modi adipisci alias aut obcaecati, ratione maiores iusto expedita praesentium voluptas porro doloribus? Illum, quae!
            Fugiat delectus ipsam cum tenetur nesciunt corporis libero praesentium veniam labore doloremque fugit doloribus facere, ut officia cupiditate enim explicabo beatae exercitationem inventore excepturi! Iure voluptates sunt autem deleniti illo.
            Repellat modi tempora ipsa aperiam quos commodi natus, officiis placeat dolorum culpa magni aliquam itaque maiores molestias, beatae quidem incidunt ab sit porro libero neque temporibus officia laudantium saepe. Corrupti.
            Quisquam et quaerat quod eaque voluptate autem qui natus, nostrum suscipit obcaecati soluta eligendi similique velit officia optio aperiam rerum provident facilis. Itaque aliquam eius ea repellendus iusto voluptates similique.
            Fugit iure eum a laboriosam? Reiciendis asperiores quo aliquam minima cumque nulla ad necessitatibus architecto possimus voluptatibus debitis repellendus, natus iste nemo quos inventore perferendis officiis repudiandae ipsam molestiae animi.
            Quis harum unde dolorem nulla distinctio tenetur, obcaecati ipsam iure ad voluptas, iste perspiciatis magni doloremque in quidem laborum officia? Cum quae vel, eligendi minus labore reiciendis animi assumenda tenetur.
            Unde corrupti quisquam enim, facere eos distinctio quas doloremque, quaerat, optio nam minus nisi perferendis sapiente accusamus quidem illum mollitia sunt possimus. Magni temporibus sit necessitatibus odit vel placeat aspernatur?
            Reprehenderit dolores corrupti cumque aspernatur ratione ullam quia deserunt, placeat repellat quaerat totam dolor id possimus nesciunt minus neque commodi provident esse nemo quod inventore omnis eligendi atque voluptatem? Voluptatem.
            Alias eligendi ab iste rem odit vel fugit voluptatem culpa vero possimus? Cumque deserunt voluptatibus, voluptatem explicabo a commodi. Asperiores omnis unde provident quaerat beatae modi voluptatem dolores officia expedita?
            Voluptatibus nulla facere dolor optio doloremque officiis odio dicta at nesciunt animi, atque exercitationem? Vitae inventore nam deserunt accusantium doloribus, iure dolore rem quae a odit ipsum, omnis quasi molestiae?
            Accusamus sit minus vero. Veritatis ipsum, a quae possimus odit totam iste alias veniam impedit omnis aliquam recusandae sunt, id quas libero exercitationem corporis nisi repellendus eveniet. Asperiores, assumenda aut.
            Quas odit nesciunt nobis placeat iure vero in? Iure magni atque asperiores, exercitationem provident ab qui distinctio dolorum deserunt, molestias officiis tenetur blanditiis fugiat cupiditate dolore quaerat unde ipsa quasi.
            Iusto molestiae laudantium odit sunt placeat in. Ab architecto deserunt vero ratione, porro quasi quia doloribus, temporibus facere odio sunt delectus exercitationem obcaecati id dolor! Sed excepturi eius commodi voluptatem.
            Odit, cupiditate. Voluptatem ipsam eum quisquam autem quam neque minima earum sapiente, cupiditate sint minus vitae vel nostrum, beatae ea blanditiis. Reprehenderit sunt libero unde officia maiores, voluptate temporibus nisi!
            Eos architecto iure, laborum ratione et ad non quis reprehenderit fugit iste voluptate animi deleniti maxime sit rem? Id magni culpa pariatur dolor quo, architecto non laboriosam neque tempora nostrum.
            Expedita at hic sequi voluptates exercitationem sapiente laboriosam ex molestias necessitatibus cum explicabo debitis, animi, dolor ab tempore culpa non? Totam ullam unde quasi delectus, laboriosam ex qui consectetur perferendis!
            Asperiores distinctio unde eos aliquid iusto. Ipsam facere consequuntur dolores hic nesciunt, nam deleniti ad illum consequatur iure autem a animi quod inventore dignissimos fugit similique nihil magnam placeat harum?
            Natus rerum quam labore cum tenetur dicta quisquam sed vel explicabo veniam, autem, quibusdam quod? Expedita ratione asperiores eum, obcaecati fugiat illo recusandae odio enim, dolor cumque eaque aperiam tenetur?
            Nihil cupiditate voluptatum corporis, reiciendis dolorem aliquam fuga modi obcaecati quos rerum ad vero qui cumque suscipit dignissimos? Corrupti recusandae nobis quis animi officiis quae earum optio cum nostrum vitae!
            Velit architecto voluptate numquam ipsa dignissimos autem, nihil officiis esse nisi quod consequuntur quos sunt perferendis vitae magni sit nobis quasi maiores aspernatur tempore nostrum veritatis? Explicabo atque minima perferendis.
            Odit cum necessitatibus quod sunt non, sint quisquam eveniet cupiditate debitis numquam laboriosam expedita praesentium vitae vel consequuntur aliquam distinctio odio excepturi voluptatum aut iure labore omnis assumenda soluta. Nam.
            Architecto, provident officiis? Soluta culpa ipsa fugit animi eligendi ad molestiae accusamus natus nisi, architecto magni quidem, maiores velit ipsam nobis voluptatum corporis. Inventore quas exercitationem voluptas mollitia! Incidunt, doloremque.
            Necessitatibus, excepturi aut culpa nesciunt praesentium officia cum dignissimos architecto sed amet vero totam, ab itaque consequatur exercitationem ipsam eius explicabo. Cum praesentium optio unde ipsa ut dolor facere quaerat!
            Autem voluptatibus necessitatibus repellat doloremque molestias eligendi veritatis eos quis rem officia labore, rerum quas vero maiores nemo magni culpa dignissimos sequi? Adipisci, totam vitae qui doloremque saepe maiores voluptatem.
            Hic pariatur ratione itaque ducimus aliquam ut veniam voluptatem earum. Cum praesentium accusantium nemo omnis maxime tempora quibusdam, laboriosam autem, id doloremque et ducimus eius inventore soluta alias dolorem dignissimos?
            Praesentium impedit consequuntur iste incidunt dolore maiores veniam ullam! Error odit odio explicabo facilis similique consequuntur, ut dolorum provident. Iste, doloremque maiores. Nisi rerum iste adipisci ullam nihil ut temporibus.
            Dolorem corporis dolores nam. Pariatur quis expedita porro dolorum! Maxime reprehenderit voluptates, dignissimos fugiat perferendis laudantium maiores unde? Beatae aspernatur odio deleniti facilis quaerat voluptatem dolore est quo ratione quisquam.
            Molestias voluptatum soluta tempora sunt similique ab porro, placeat explicabo illum, impedit ullam, obcaecati eaque voluptates quod totam corrupti quasi delectus odio dolore maiores nam excepturi dignissimos veniam. Doloribus, vero.
            Ipsa molestiae obcaecati ex, sed beatae natus qui aliquam quibusdam mollitia tempore, id aliquid, doloremque et voluptas numquam dicta voluptates nihil? Ratione, nihil vitae. Nisi quia maiores ex optio quod!
            Quam repellat rerum, veritatis enim incidunt placeat suscipit amet sequi qui facilis! Cum cupiditate enim illo qui sint nostrum magni porro asperiores commodi exercitationem, incidunt maxime ipsum aperiam corporis! Corrupti!
            Aut ab quae architecto magnam repellat quo numquam eveniet ipsam? Nihil eveniet quidem a repudiandae nisi? Recusandae voluptas totam, ex expedita ab nam rerum qui consequuntur, eos et laudantium tempora.
            Aliquid doloremque fugit velit? Quibusdam cupiditate ullam, sapiente voluptatem quam quas consectetur ipsa similique? Dolores inventore libero, optio aut soluta ratione exercitationem reprehenderit consequuntur, consequatur voluptatum nesciunt error, assumenda architecto.
            Modi possimus, quod quos consectetur dolores ut! Voluptatem quas inventore deserunt, eligendi saepe magni laboriosam ipsum animi est sit quae commodi non deleniti recusandae ex praesentium explicabo reprehenderit odit error.
            Rem distinctio odit exercitationem voluptatum nesciunt, iste dolorum esse, temporibus est ut laudantium commodi, repudiandae dolor officia! Soluta facere sapiente aspernatur ratione delectus, earum libero accusantium, eos modi iste explicabo!
            Voluptatibus reiciendis saepe architecto ea! Enim doloremque quam a optio maiores voluptas natus incidunt! Omnis placeat, ipsum eos nulla nobis qui incidunt magnam unde dignissimos itaque molestiae velit earum commodi.
            Tempora eum laudantium veritatis iure totam, voluptas quas labore deleniti ut officiis cumque cum nostrum repudiandae maiores quia suscipit optio! Fuga molestias cum inventore minus quae deserunt qui eos reiciendis?
            Enim aut nesciunt saepe fuga suscipit et perferendis. Repudiandae velit debitis quis earum aspernatur, recusandae, ad doloribus aliquam quae amet fuga architecto ut atque iusto aperiam quod itaque odio sit!
            Repudiandae, excepturi sint consequatur minus beatae ipsam. Molestiae cumque eius magni odit non iste fugit optio. Commodi rem quod cum provident laboriosam obcaecati non. Adipisci sint laboriosam voluptas dolores vitae?
            Ipsa pariatur temporibus tenetur ea consectetur totam. Voluptas quis quae commodi quidem ipsum iusto eos? Accusantium veniam animi, odio natus obcaecati, dolorem est quisquam assumenda optio atque quia ducimus numquam.
            Voluptas provident saepe libero quos qui, voluptatem molestiae nihil voluptatum natus ea at vel iure quam necessitatibus corrupti eius consectetur repudiandae minus itaque soluta. Nesciunt molestias iure sapiente impedit dicta!
            Vero illum sapiente quaerat omnis provident et amet, nulla eum, perferendis sed, aliquam vitae quam architecto deserunt? Quod perspiciatis error nostrum labore eveniet iste, unde ad expedita quas corporis neque?
            Eos, non. Quis ipsam natus, maiores ex maxime consectetur at repellendus reprehenderit excepturi doloribus fugit eum aliquid veniam possimus! Necessitatibus, quae? Quibusdam aliquid sed consequuntur nostrum suscipit quo, veritatis quidem!
            Alias vero praesentium neque corporis, illum enim, blanditiis eveniet incidunt iste est inventore. Sit animi distinctio, dicta quae minus magnam quia suscipit odio modi sapiente consequatur vitae qui ab pariatur.
            Quis nemo sunt voluptatem iure recusandae enim ea, sapiente eaque illum maxime, iusto eos. Corrupti non necessitatibus modi accusantium labore distinctio ipsum consectetur, maxime alias dolorem voluptatum laboriosam dicta tempore!
            Repellat delectus modi veritatis adipisci fuga expedita beatae, repudiandae iste non ad eveniet ipsa, voluptatum omnis tempora cum perspiciatis laboriosam praesentium laudantium exercitationem illum sunt amet ipsum nobis. Quis, asperiores!
            Dolor et voluptates minima ex ducimus nam obcaecati? Repudiandae atque excepturi deserunt velit, inventore alias neque error itaque possimus, tempora magnam provident ipsam autem rerum magni iusto sed quas! A.
            Cupiditate nam molestiae mollitia nihil aliquid ea quidem nobis cumque modi, aspernatur temporibus id atque! Deserunt in, cupiditate sed laboriosam et dolore temporibus eos id eum ipsa illo, doloremque nemo.
            Natus labore laudantium architecto quae, voluptate alias minus sequi delectus quis fugiat sed iure earum non id dolore, saepe rerum tempora maiores dolores unde itaque. Totam dignissimos ratione eaque at!
            Dolorum vitae neque nam, rem illo facilis porro voluptatum hic ipsam cumque voluptatem voluptates! Quaerat a dignissimos adipisci quisquam enim quo. Deleniti maiores fugiat beatae non magni, nisi dignissimos porro?
            Magnam quae aliquid animi laboriosam veritatis eius, quod deserunt! Accusamus possimus animi, at quam nulla amet quia culpa quaerat recusandae nemo neque minus laborum expedita exercitationem natus saepe aliquid? Ad?
            Molestias est ipsum, praesentium dolorum sapiente magnam dolor aut, in animi hic tempora natus quaerat delectus, incidunt sed! Ab pariatur perspiciatis error facere quod voluptatibus laborum laboriosam officia mollitia qui!
            Recusandae tempora aperiam eos! Voluptatibus aliquam beatae perferendis commodi error distinctio, ullam aut quia saepe officiis, atque illum fugiat, quo maiores est omnis. Nemo, quidem delectus? In repellat ipsa quae!
            Sapiente facere, cumque, nobis ut quis sit veniam doloribus iste repudiandae neque quo tempora tempore! Eaque tenetur ipsum rerum, beatae hic delectus in perferendis facere! Sed in iste sequi velit.
            Fuga perspiciatis modi non nulla delectus sapiente illo rem facere quasi perferendis blanditiis, quis omnis necessitatibus tempora sed corporis ipsa molestiae consectetur id et officiis veritatis amet ea. Aut, ad.
            Odit possimus a optio sunt ducimus, soluta maxime numquam minus! Fugiat optio nostrum ab vel corporis aliquid labore asperiores! Necessitatibus, ipsam. Nisi tempora nemo provident culpa aliquam laudantium quo facere.
            Eaque necessitatibus perspiciatis atque odio fuga consequatur nisi inventore sed reprehenderit porro consequuntur numquam, dicta culpa exercitationem commodi asperiores facere ut. Suscipit cum deserunt repellendus! Amet voluptas dolore molestias doloribus?
            Harum facilis doloribus modi, nesciunt explicabo minus officiis et aliquid? Tempora accusantium pariatur sequi delectus magnam exercitationem, ipsum cum eligendi consequatur praesentium error unde inventore iusto deleniti temporibus commodi. Illo.
            Iste dignissimos dicta, ipsa eveniet illo recusandae. Dicta voluptatum velit commodi unde asperiores quos saepe maxime quae, vitae numquam pariatur excepturi amet ipsum adipisci ratione placeat ipsa! Quibusdam, tempore cum!
            Repellat corrupti iusto porro atque possimus aspernatur explicabo odit, quidem, quaerat, eveniet suscipit tenetur! Veritatis qui doloremque eligendi ut, praesentium culpa, harum commodi voluptatibus dolor, sed laudantium hic? Sunt, vero.
            Iste cumque aut ad aliquid facere saepe odit minima itaque, nam a, quia commodi incidunt corrupti tempora, ducimus similique totam amet ipsum dolores! Labore nisi asperiores hic non repellat nesciunt.
            Suscipit exercitationem deleniti animi. Vitae hic debitis aperiam inventore laborum sit fugiat beatae, nihil maxime saepe autem cumque excepturi voluptate nemo illo omnis. Nisi natus dicta facere nostrum tenetur id.
            Vero maiores neque repellat, hic pariatur tenetur dolorum beatae assumenda perspiciatis saepe sequi. Officiis repellat, quia perspiciatis asperiores fugit voluptate magni, eligendi in placeat, maiores voluptatem excepturi perferendis praesentium id.
            Magni dolores, magnam sit corrupti fugiat dicta nihil excepturi sunt minus repellat necessitatibus dolorum dignissimos. Tempore expedita eaque soluta laborum doloribus, architecto ut excepturi nulla quos quas fugiat, animi voluptates.
            Eos voluptates necessitatibus quos, consequatur excepturi voluptatibus molestias atque minus numquam repellendus, officiis ex itaque, explicabo ab voluptatem hic adipisci. Illum quae, velit doloribus ex vitae distinctio aspernatur aliquid quaerat.
            Ipsa repudiandae quod dolor debitis. Enim sunt unde expedita, qui laudantium tempore omnis quidem nesciunt ipsum, fuga, nostrum delectus. Hic magni quasi temporibus dolore. Magnam deleniti repellendus tempora expedita labore.
            Et modi voluptates labore itaque a. Reiciendis corporis, eligendi exercitationem, nemo quis maiores similique officia laboriosam pariatur aspernatur facilis dolorem minima eius corrupti officiis sint aliquam aperiam beatae quidem tenetur.
            Et sed, accusantium ipsam reiciendis laudantium esse dignissimos at est libero officia velit nobis eum exercitationem voluptates explicabo dicta qui maiores, quidem aliquam maxime in? Amet, debitis quae? Expedita, hic.
            Illo itaque asperiores dolores excepturi nostrum iure cum harum similique sequi accusamus, tempora iste blanditiis esse nam quas molestias pariatur non quia repellat velit veniam impedit fuga? Facere, aut vel?
            Quam iure asperiores nesciunt placeat voluptatum suscipit minus perferendis expedita laborum amet labore libero incidunt, odio voluptas natus accusantium. Quos illum temporibus omnis ut, nam ratione iste suscipit soluta ad.
            Quidem ipsum facilis, velit unde ipsa suscipit sapiente cum, cupiditate libero rem necessitatibus in accusantium inventore ullam, optio quae quo enim? Accusamus molestias est illo enim amet excepturi fugit blanditiis?
            Quis voluptatibus sit non. Fugiat excepturi praesentium eius hic. Et odio aperiam similique aliquid natus molestiae voluptate nulla iusto veniam laudantium animi fuga necessitatibus doloribus enim reprehenderit, quibusdam, soluta ipsum!
            Voluptas veniam facere autem odit reprehenderit. Temporibus, non possimus. Sit, accusantium a reiciendis corporis amet, reprehenderit aut animi quisquam excepturi accusamus similique, facilis odio autem atque perferendis praesentium debitis. Maiores.
            Cum incidunt consequuntur quam non vitae, labore doloremque dolore rem illo eius consectetur aspernatur! Veniam libero sapiente eos pariatur dolores voluptatibus, enim mollitia? Eius quidem vero minus neque at eaque.
            Molestiae deleniti impedit culpa placeat ipsum quae magni adipisci quibusdam, earum voluptas id voluptatibus perspiciatis quia repellat assumenda voluptatum praesentium numquam dolor. Quidem, itaque porro! Officia similique magnam laboriosam inventore.
            Similique eum vitae cum reiciendis quia explicabo omnis magnam, repellendus accusamus molestiae facilis sapiente delectus numquam sequi ea suscipit vel sunt ut assumenda consectetur aliquid. Error nesciunt amet culpa fuga!
            Minima consequatur provident dolores placeat eius recusandae. Velit maxime debitis id illum repellendus voluptatem dolor molestiae, repudiandae inventore nulla sed incidunt perspiciatis cum expedita unde dolore earum aut laboriosam possimus?
            Molestias impedit dolorum vero odio porro! Cupiditate beatae adipisci veniam reiciendis ipsam! Ipsa, quo harum officiis possimus non nobis eius, ad ipsum est quam accusamus sed aliquid blanditiis earum modi?
            Molestias accusamus non quasi ea vitae voluptatibus debitis minima dolore eos, adipisci atque doloremque perferendis nam asperiores sed cum dolorum aut facilis, pariatur magnam iusto magni alias ab. Deleniti, fuga.
            Alias nisi porro omnis ratione, ducimus sed. Aspernatur maiores esse, laborum quis accusamus earum iste totam sint aut a pariatur, nesciunt, sed dicta neque eligendi facere qui distinctio quisquam culpa?
            Praesentium libero mollitia ducimus perferendis explicabo fuga molestias aliquam inventore dolor recusandae, aliquid at adipisci, esse porro nihil. Consequuntur, necessitatibus repudiandae tempore recusandae expedita deserunt? Sunt cumque sapiente nisi explicabo!
            Maxime quisquam cupiditate, consequuntur pariatur id cumque debitis veritatis aut sit saepe neque quas facilis consequatur tenetur obcaecati numquam soluta vero fuga quo natus ipsam. Minima autem mollitia nisi magnam?
            Quibusdam quaerat perferendis aperiam consequuntur fuga eius nesciunt sequi quo, illo, voluptatibus labore in repellat temporibus, voluptatem nihil itaque officia vero quasi odio non provident ea. Eos itaque eveniet possimus?
            Earum quaerat distinctio nulla, suscipit id sunt, molestiae tempore ullam quis at impedit quasi sint aliquid enim? Veniam accusantium non dolorem odit doloremque amet aliquid odio? Tenetur, perspiciatis eum. Vitae!
            Dolor harum qui eaque aliquid. Quas, voluptate eius. Assumenda nulla nihil suscipit exercitationem, impedit nisi? Harum labore quod totam, minus dolorum quidem doloribus quis vitae accusantium, placeat, magnam quos sint?
        </div>
    </div>
    </>
  )
}

export default Home